"""Generate v2.11 Qwen-narrative pack.

Targets v2.9 OOD-benchmark gaps with rich Greek prose generated by
Qwen3.6-35B-A3B served locally via llama-server (Docker).

Strategy:
  - PII slot values authored deterministically (so spans are exact).
  - Qwen writes natural Greek prose embedding the slot values verbatim.
  - 5 narrow registers targeted at v2.X failure modes:
      * vocative_letter_formal       — title + surname (vocative case)
      * tax_office_email_dense       — multi-PII tax email
      * medical_record_narrative     — patient name + ΑΜΚΑ + dates
      * informal_sms_dense           — first-name vocative SMS w/ multi-PII
      * passport_application_letter  — adt/afm in narrative letter context
  - Weighted PII picker — 3x weight on amka / person / ama, normal weight
    on others. Pushes the model toward hardest classes.

Usage:
    python scripts/data_packs/generate_qwen_narrative_pack.py \\
        --output data/processed/v2_11_qwen_pack.jsonl \\
        --target-count 1500 --batch-size 10 --seed 2031 \\
        --host http://localhost:8080
"""
from __future__ import annotations

import argparse
import json
import random
import re
import string
import sys
import time
import urllib.request
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT / "scripts"))
sys.path.insert(0, str(PROJECT_ROOT / "scripts" / "data_packs"))

from generate_commercial_safe_greek_pii import (  # noqa: E402
    gen_person,
    gen_phone,
    gen_email,
    gen_address,
    gen_date,
)


# ─── Value-only generators (NO prefix tokens; v2 OPF convention) ──

def gen_amka(rng: random.Random) -> str:
    return "".join(rng.choices(string.digits, k=11))


def gen_afm(rng: random.Random) -> str:
    return "".join(rng.choices(string.digits, k=9))


def gen_adt(rng: random.Random) -> str:
    greek_letters = "ΑΒΓΔΕΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩ"
    letters = "".join(rng.choices(greek_letters, k=rng.choice([2, 3])))
    digits = "".join(rng.choices(string.digits, k=6))
    sep = rng.choice(["-", " ", ""])
    return f"{letters}{sep}{digits}"


def gen_ama(rng: random.Random) -> str:
    return "".join(rng.choices(string.digits, k=rng.choice([7, 9])))


def gen_dl(rng: random.Random) -> str:
    return "".join(rng.choices(string.digits, k=9))


def gen_gemi(rng: random.Random) -> str:
    return "".join(rng.choices(string.digits, k=12))


# Weighted picker — 3x for hardest classes, 1x others
PII_GENERATORS_WEIGHTED: list[tuple[str, callable, float]] = [
    ("private_person", gen_person, 4.0),
    ("amka",           gen_amka,   3.0),
    ("ama",            gen_ama,    3.0),
    ("afm",            gen_afm,    2.5),
    ("adt",            gen_adt,    2.0),
    ("driver_license", gen_dl,     1.5),
    ("private_phone",  gen_phone,  1.5),
    ("private_email",  gen_email,  1.0),
    ("private_address",gen_address,1.0),
    ("private_date",   gen_date,   1.0),
    ("gemi",           gen_gemi,   1.0),
]

PII_LABELS_DESC = {
    "private_person":  "ονοματεπώνυμο",
    "amka":            "ΑΜΚΑ",
    "ama":             "ΑΜΑ ΙΚΑ",
    "afm":             "ΑΦΜ",
    "adt":             "ΑΔΤ",
    "driver_license":  "δίπλωμα οδήγησης",
    "private_phone":   "τηλέφωνο",
    "private_email":   "email",
    "private_address": "διεύθυνση",
    "private_date":    "ημερομηνία",
    "gemi":            "ΓΕΜΗ",
}


def _pick_pii_set(rng: random.Random, k: int) -> list[tuple[str, str]]:
    cats = [c for c, _, _ in PII_GENERATORS_WEIGHTED]
    weights = [w for _, _, w in PII_GENERATORS_WEIGHTED]
    chosen: list[str] = []
    available = list(zip(cats, weights))
    while len(chosen) < k and available:
        total = sum(w for _, w in available)
        r = rng.uniform(0, total)
        upto = 0.0
        for i, (c, w) in enumerate(available):
            upto += w
            if upto >= r:
                chosen.append(c)
                available.pop(i)
                break
    pairs = []
    for c in chosen:
        gen = next(g for n, g, _ in PII_GENERATORS_WEIGHTED if n == c)
        pairs.append((c, gen(rng)))
    return pairs


# ─── Narrow registers targeting v2.X gaps ──────────────────────────

REGISTERS: list[tuple[str, str]] = [
    (
        "επίσημη επιστολή με κλητική προσφώνηση",
        "Επίσημη επιστολή 30-60 λέξεων με αρχή «Αξιότιμε κ. ΕΠΩΝΥΜΟ,» ή "
        "«Κύριε ΕΠΩΝΥΜΟ,» ή «Δρ. ΕΠΩΝΥΜΟ,» — όπου ΕΠΩΝΥΜΟ είναι το επώνυμο "
        "του ονοματεπωνύμου από τις τιμές. Δομή: προσφώνηση, σύντομη "
        "παράγραφος, αναφορά σε όλες τις τιμές της πρότασης.",
    ),
    (
        "tax-office email πυκνό",
        "Email από ΔΟΥ ή ΑΑΔΕ προς πολίτη, 25-50 λέξεις, με ονοματεπώνυμο "
        "+ ΑΦΜ + ΑΜΚΑ ή/και ΑΔΤ ενσωματωμένα φυσικά στη ροή. Παράδειγμα "
        "ύφους: «Σας ενημερώνουμε ότι εκκρεμεί η υποβολή της δήλωσης Ε1 "
        "για τον φορολογούμενο [όνομα], ΑΦΜ [αφμ]…».",
    ),
    (
        "ιατρική καταγραφή",
        "Σημείωμα ιατρικού φακέλου ή παραπεμπτικού 25-45 λέξεις με "
        "ασθενή (ονοματεπώνυμο) + ΑΜΚΑ + πιθανή ημερομηνία ή επικοινωνία. "
        "Τόνος επαγγελματικός, π.χ. «Παραπέμπεται ο/η [όνομα], ΑΜΚΑ "
        "[ΑΜΚΑ], για αιματολογικές εξετάσεις…».",
    ),
    (
        "informal SMS με πολλά PII",
        "Σύντομο SMS 15-35 λέξεις, άτυπο, ενδεχομένως χωρίς πλήρη σημεία "
        "στίξης, με κλητική πρώτου ονόματος (π.χ. «Γιάννη» ή «Μαρία») + "
        "1-2 αριθμητικά PII. Π.χ. «Μαρία στείλε μου ΑΦΜ σου [αφμ] και "
        "ΑΜΚΑ [ΑΜΚΑ] να τα δώσω στον λογιστή».",
    ),
    (
        "ασφαλιστικό έγγραφο ΕΦΚΑ/ΙΚΑ",
        "Καταγραφή/βεβαίωση ασφάλισης 25-45 λέξεις από ΕΦΚΑ ή ΙΚΑ με "
        "ασφαλισμένο (ονοματεπώνυμο) + ΑΜΑ ΙΚΑ + ΑΜΚΑ. Π.χ. «Ο/Η [όνομα] "
        "με ΑΜΑ ΙΚΑ [ΑΜΑ] και ΑΜΚΑ [ΑΜΚΑ] εγγράφεται από 1/1/2026…».",
    ),
    (
        "αίτηση διπλώματος/διαβατηρίου",
        "Αίτημα ή απόφαση 25-50 λέξεις σχετικά με δίπλωμα οδήγησης ή "
        "διαβατήριο, με ονοματεπώνυμο + ΑΔΤ ή/και αριθμό διπλώματος + "
        "ΑΦΜ. Π.χ. «Στοιχεία αιτούντος [όνομα], ΑΔΤ [ΑΔΤ], ζητά αντίγραφο "
        "διπλώματος αρ. [δίπλωμα]…».",
    ),
]

_SYS_PROMPT = (
    "Είσαι παραγωγός ελληνικού κειμένου για NER training. "
    "Παράγεις φυσικές, σύντομες ελληνικές προτάσεις ενσωματώνοντας "
    "ΑΥΤΟΥΣΙΕΣ τις τιμές που σου δίνονται. ΟΧΙ σχόλια, ΟΧΙ σκέψεις."
)

_NUM_LINE_RE = re.compile(r"^\s*(\d{1,3})[\.\)]\s+(.*)$")


def _build_prompt(register_name: str, register_desc: str,
                  items: list[list[tuple[str, str]]]) -> str:
    lines = []
    for i, pairs in enumerate(items, start=1):
        parts = [f"{PII_LABELS_DESC.get(c, c)}: {v}" for c, v in pairs]
        lines.append(f"{i}. " + "  +  ".join(parts))
    values_block = "\n".join(lines)
    return (
        f"Ύφος: {register_name}.\n"
        f"Οδηγίες ύφους: {register_desc}\n\n"
        f"Γράψε ΑΚΡΙΒΩΣ {len(items)} αριθμημένες προτάσεις (1., 2., …) σε αυτό "
        "το ύφος. Κάθε αριθμημένη πρόταση πρέπει να περιέχει ΑΥΤΟΥΣΙΕΣ ΟΛΕΣ "
        "τις τιμές με τον ίδιο αριθμό.\n\n"
        f"Τιμές ανά πρόταση:\n{values_block}\n\n"
        "Κανόνες:\n"
        "- Οι τιμές εμφανίζονται ΑΥΤΟΥΣΙΕΣ (ίδια κεφαλαία/πεζά, παύλες, κενά).\n"
        "- ΜΗΝ προσθέτεις τις ετικέτες («ΑΦΜ», «ΑΜΚΑ») πριν την τιμή αν δεν "
        "  ταιριάζει στη ροή του λόγου — ενσωμάτωσε τις φυσικά.\n"
        "- Κάθε πρόταση σε ΞΕΧΩΡΙΣΤΗ γραμμή με αριθμό «1.», «2.», …\n"
        "- 25-50 λέξεις ανά πρόταση (όπως ορίζει το ύφος).\n"
        "- Χωρίς εισαγωγή, χωρίς εξήγηση, χωρίς εισαγωγικά."
    )


def _call_qwen(host: str, system: str, user: str,
               temperature: float = 0.8, max_tokens: int = 2400) -> str:
    body = json.dumps({
        "model": "qwen",
        "messages": [
            {"role": "system", "content": system},
            {"role": "user",   "content": user},
        ],
        "temperature": temperature,
        "max_tokens": max_tokens,
        "chat_template_kwargs": {"enable_thinking": False},
    }).encode("utf-8")
    req = urllib.request.Request(
        f"{host}/v1/chat/completions",
        data=body,
        headers={"Content-Type": "application/json"},
    )
    with urllib.request.urlopen(req, timeout=600) as resp:
        d = json.loads(resp.read().decode("utf-8"))
    return d["choices"][0]["message"]["content"]


def _parse_records(content: str, items: list[list[tuple[str, str]]],
                   register_name: str) -> list[dict]:
    parsed: dict[int, str] = {}
    for line in content.splitlines():
        m = _NUM_LINE_RE.match(line)
        if not m:
            continue
        idx = int(m.group(1)) - 1
        text = m.group(2).strip()
        if 0 <= idx < len(items) and text and idx not in parsed:
            parsed[idx] = text

    out: list[dict] = []
    for idx, pairs in enumerate(items):
        text = parsed.get(idx)
        if not text:
            continue
        labels: list[dict] = []
        cursor = 0
        ok = True
        for category, value in pairs:
            pos = text.find(value, cursor)
            if pos < 0:
                pos = text.find(value)  # try anywhere
            if pos < 0:
                ok = False
                break
            labels.append({"category": category, "start": pos, "end": pos + len(value)})
            cursor = pos + len(value)
        if not ok or not labels:
            continue
        labels.sort(key=lambda sp: sp["start"])
        out.append({
            "text": text,
            "label": labels,
            "info": {
                "source": "v2_11_qwen_narrative",
                "domain": f"register:{register_name}",
                "strategy": "qwen3.6-35b-a3b/local",
            },
        })
    return out


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--target-count", type=int, default=1500)
    parser.add_argument("--batch-size", type=int, default=10)
    parser.add_argument("--seed", type=int, default=2031)
    parser.add_argument("--host", default="http://localhost:8080")
    parser.add_argument("--max-batches", type=int, default=400,
                        help="Hard cap on Qwen calls (safety).")
    args = parser.parse_args()

    rng = random.Random(args.seed)
    args.output.parent.mkdir(parents=True, exist_ok=True)

    # PII per record: 1 (40%), 2 (40%), 3 (20%)
    weights = [0.4, 0.4, 0.2]

    written = 0
    batches = 0
    skipped = 0
    t_start = time.time()
    by_register: dict[str, int] = {r: 0 for r, _ in REGISTERS}

    with open(args.output, "w", encoding="utf-8") as f:
        while written < args.target_count and batches < args.max_batches:
            batches += 1
            register_name, register_desc = rng.choice(REGISTERS)
            items: list[list[tuple[str, str]]] = []
            for _ in range(args.batch_size):
                k = rng.choices([1, 2, 3], weights=weights, k=1)[0]
                items.append(_pick_pii_set(rng, k))

            user_prompt = _build_prompt(register_name, register_desc, items)
            try:
                t0 = time.time()
                content = _call_qwen(args.host, _SYS_PROMPT, user_prompt)
                t_call = time.time() - t0
            except Exception as e:
                print(f"[batch {batches}] CALL FAILED: {e}", flush=True)
                continue

            recs = _parse_records(content, items, register_name)
            for r in recs:
                f.write(json.dumps(r, ensure_ascii=False) + "\n")
            f.flush()
            written += len(recs)
            skipped += args.batch_size - len(recs)
            by_register[register_name] += len(recs)
            elapsed = time.time() - t_start
            rate = written / elapsed if elapsed > 0 else 0
            eta = (args.target_count - written) / rate if rate > 0 else float("inf")
            print(f"[batch {batches:>3} {t_call:5.1f}s] "
                  f"{register_name[:30]:<30} +{len(recs)}/{args.batch_size} "
                  f"total={written}/{args.target_count} "
                  f"({rate*60:.1f}/min, ETA {eta/60:.0f}min)",
                  flush=True)

    print(f"\n=== DONE ===")
    print(f"Wrote {written} records in {batches} batches "
          f"({(time.time()-t_start)/60:.1f} min, {skipped} skipped)")
    print("Per-register:", json.dumps(by_register, ensure_ascii=False))


if __name__ == "__main__":
    main()
